#define SCREEN_WIDTH 256
#define SCREEN_HEIGHT 192

#define WORLD_WIDTH 64
#define WORLD_HEIGHT 12
#define TILE_SIZE 16
#define PLAYER_SIZE 16
#define RAILS_Y 5

#define MAX_CLIENTS 1 // Keep it 2 players max, for now
#define MAX_UPDATES 16

enum Objects
{
    EMPTY,
    TILE_EMPTY,
    TILE_TREE,
    TILE_ROCK,
    OBJECT_RAIL = 8,
    OBJECT_WOOD,
    OBJECT_IRON,
    OBJECT_AXE,
    OBJECT_PICKAXE
};

enum Directions
{
    DIR_DOWN,
    DIR_LEFT,
    DIR_RIGHT,
    DIR_UP
};

enum Gamemodes
{
    GAMEMODE_SINGLEPLAYER,
    GAMEMODE_HOST,
    GAMEMODE_CLIENT,
    GAMEMODE_ASSISTED
};

enum Actions
{
    ACTION_SETWORLDTERRAIN,
    ACTION_SETWORLDOBJECT,
    ACTION_SETWORLDHEALTH,
    ACTION_SETWAGONOBJECT,
    ACTION_SETWAGONQUANTITY,
    ACTION_SETPLAYEROBJECTHELD,
    ACTION_SETPLAYERQUANTITY
};

enum SearchStates
{
    SEARCH_IDLE,
    SEARCH_SEARCHING,
    SEARCH_RETURNING,
    SEARCH_BLOCKED
};