#define SCREEN_WIDTH 256
#define SCREEN_HEIGHT 192

#define WORLD_WIDTH 64
#define WORLD_HEIGHT 12
#define TILE_SIZE 16
#define PLAYER_SIZE 16

#define EMPTY 0
#define TILE_EMPTY 1
#define TILE_TREE 2
#define TILE_ROCK 3
#define OBJECT_RAIL 8
#define OBJECT_WOOD 9
#define OBJECT_IRON 10
#define OBJECT_AXE 11
#define OBJECT_PICKAXE 12

#define DIR_DOWN 0
#define DIR_LEFT 1
#define DIR_RIGHT 2
#define DIR_UP 3

#define GAMEMODE_SINGLEPLAYER 0
#define GAMEMODE_HOST 1
#define GAMEMODE_CLIENT 2
#define GAMEMODE_ASSISTED 3

#define ACTION_SETWORLDTERRAIN 0
#define ACTION_SETWORLDOBJECT 1
#define ACTION_SETWORLDHEALTH 2
#define ACTION_SETWAGONOBJECT 3
#define ACTION_SETWAGONQUANTITY 4
#define ACTION_SETPLAYEROBJECTHELD 5
#define ACTION_SETPLAYERQUANTITY 6

#define SEARCH_IDLE 0
#define SEARCH_SEARCHING 1
#define SEARCH_RETURNING 2
#define SEARCH_BLOCKED 3

#define MAX_CLIENTS 1 // Keep it 2 players max, for now
#define MAX_UPDATES 16